import { describe, expect, it } from "vitest";
import {
  hasGeneratedMarker,
  hasSourceMapReference,
  isMinified,
} from "./file-analysis.js";

describe("file-analysis", () => {
  describe("isMinified", () => {
    it("returns true for single long line JS", () => {
      const content = "function a(){" + "a".repeat(600) + "}";
      expect(isMinified(content, ".js")).toBe(true);
    });

    it("returns true for few lines with large size", () => {
      const content =
        "line1\n" + "line2\n" + "line3\n" + "a".repeat(10005) + "\n";
      expect(isMinified(content, ".css")).toBe(true);
    });

    it("returns false for normal code", () => {
      const content = `
        function hello() {
          console.log("world");
          return true;
        }
      `;
      expect(isMinified(content, ".js")).toBe(false);
    });

    it("ignores irrelevant extensions", () => {
      const content = "a".repeat(600);
      expect(isMinified(content, ".txt")).toBe(false);
    });
  });

  describe("hasGeneratedMarker", () => {
    it("detects Go generated file", () => {
      const content =
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main";
      expect(hasGeneratedMarker(content)).toBe(true);
    });

    it("detects generic Generated by", () => {
      const content = "// Generated by some-tool\nvar a = 1;";
      expect(hasGeneratedMarker(content)).toBe(true);
    });

    it("detects Python/Ruby style", () => {
      const content = "# Generated by generator.rb\nclass A";
      expect(hasGeneratedMarker(content)).toBe(true);
    });

    it("returns false for normal file", () => {
      const content = "import fs from 'fs';\n// some comment";
      expect(hasGeneratedMarker(content)).toBe(false);
    });

    it("checks only first 10 lines", () => {
      const lines = Array(15).fill("line");
      lines[12] = "// Generated by tool";
      expect(hasGeneratedMarker(lines.join("\n"))).toBe(false);
    });
  });

  describe("hasSourceMapReference", () => {
    it("detects sourceMappingURL", () => {
      const content = "code();\n//# sourceMappingURL=file.js.map";
      expect(hasSourceMapReference(content)).toBe(true);
    });

    it("detects sourceURL", () => {
      const content = "code();\n//# sourceURL=file.js";
      expect(hasSourceMapReference(content)).toBe(true);
    });

    it("detects css source map", () => {
      const content =
        "body { color: red; }\n/*# sourceMappingURL=style.css.map */";
      expect(hasSourceMapReference(content)).toBe(true);
    });

    it("returns false if not present", () => {
      const content = "code();\n// regular comment";
      expect(hasSourceMapReference(content)).toBe(false);
    });
  });
});
