/**
 * Detects if a file content looks like minified code.
 * Heuristics based on GitHub Linguist.
 */
export function isMinified(content: string, extension: string): boolean {
  // Only check relevant extensions
  if (![".js", ".css", ".mjs", ".ts", ".jsx", ".tsx"].includes(extension)) {
    return false;
  }

  const lines = content.split("\n");
  if (lines.length === 0) {
    return false;
  }

  // Heuristic 1: Very high average line length
  const avgLineLength = content.length / lines.length;
  if (avgLineLength > 500) {
    return true;
  }

  // Heuristic 2: Few lines but large size (e.g. one long line)
  if (lines.length < 10 && content.length > 10000) {
    return true;
  }

  return false;
}

const GENERATED_MARKERS = [
  /^\/\/ Code generated .* DO NOT EDIT/i,
  /^\/\/ Generated by /i,
  /^# Generated by /i,
  /^\/\* Generated by /i,
  /^\/\/ This file is automatically generated/i,
  /^# This file is automatically generated/i,
  /^\/\/ AUTO-GENERATED/i,
  /^# AUTO-GENERATED/i,
  /^\/\*\s*eslint-disable\s*\*\/\s*$/, // Often used in generated files
];

/**
 * Detects if a file has a generated code marker in the header.
 * Checks the first 10 lines.
 */
export function hasGeneratedMarker(content: string): boolean {
  const firstLines = content.split("\n").slice(0, 10);
  return firstLines.some((line) =>
    GENERATED_MARKERS.some((marker) => marker.test(line.trim())),
  );
}

/**
 * Detects if a file has a source map reference at the end.
 * Checks the last 3 lines.
 */
export function hasSourceMapReference(content: string): boolean {
  const lines = content.split("\n");
  const lastLines = lines.slice(-3);
  return lastLines.some(
    (line) =>
      /^\/[/*][@#]\s*sourceMappingURL=/.test(line.trim()) ||
      /^\/[/*][@#]\s*sourceURL=/.test(line.trim()),
  );
}
