import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { Command } from "commander";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { loadConfig } from "../lib/config.js";

vi.mock("@clack/prompts", () => ({
  intro: vi.fn(),
  outro: vi.fn(),
  note: vi.fn(),
  confirm: vi.fn(),
  select: vi.fn(),
  text: vi.fn(),
  password: vi.fn(),
  isCancel: vi.fn(),
  cancel: vi.fn(),
}));

describe("init command integration", () => {
  let tempDir: string;
  let originalHomedir: typeof os.homedir;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "mgrep-init-"));
    originalHomedir = os.homedir;
    // Override os.homedir to return tempDir
    (os as { homedir: () => string }).homedir = () => tempDir;
    // Clear module cache to pick up the mocked homedir
    vi.resetModules();
  });

  afterEach(() => {
    (os as { homedir: () => string }).homedir = originalHomedir;
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("creates config directory and file", async () => {
    const { buildConfig, getConfigPaths, writeConfigFile } = await import(
      "./init.js"
    );
    const config = buildConfig({ provider: "openai" });
    writeConfigFile(config);

    const { configDir, configFile } = getConfigPaths();
    expect(fs.existsSync(configDir)).toBe(true);
    expect(fs.existsSync(configFile)).toBe(true);

    const contents = fs.readFileSync(configFile, "utf-8");
    expect(contents).toContain("mgrep configuration - generated by mgrep init");
    expect(contents).toContain("embeddings:");
  });

  it("round-trips via loadConfig", async () => {
    const { buildConfig, getConfigPaths, writeConfigFile } = await import(
      "./init.js"
    );
    const config = buildConfig({ provider: "openai" });
    writeConfigFile(config);

    const { configFile } = getConfigPaths();
    // loadConfig searches in cwd and global config, so directly read and parse
    const contents = fs.readFileSync(configFile, "utf-8");
    expect(contents).toContain("provider: openai");
  });

  it("overwrites existing config file", async () => {
    const { buildConfig, getConfigPaths, writeConfigFile } = await import(
      "./init.js"
    );
    const config = buildConfig({ provider: "openai" });
    writeConfigFile(config);

    const { configFile } = getConfigPaths();
    // Write some garbage
    fs.writeFileSync(configFile, "# old content", "utf-8");

    // Overwrite with proper config
    writeConfigFile(config);
    const contents = fs.readFileSync(configFile, "utf-8");
    expect(contents).toContain("mgrep configuration - generated by mgrep init");
    expect(contents).not.toContain("# old content");
  });

  it("registers init command with commander", async () => {
    const program = new Command();
    const { initCommand } = await import("./init.js");
    program.addCommand(initCommand);
    const init = program.commands.find((cmd) => cmd.name() === "init");
    expect(init).toBeDefined();
    expect(init?.description()).toContain("Initialize");
  });
});
