import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import * as p from "@clack/prompts";
import { Command } from "commander";
import YAML from "yaml";

const CONFIG_DIR = path.join(os.homedir(), ".config", "mgrep");
const CONFIG_FILE = path.join(CONFIG_DIR, "config.yaml");

type ProviderType = "openai" | "google" | "anthropic" | "ollama";

type ProviderDefaults = {
  embeddingModel: string;
  embeddingProvider: ProviderType;
  llmModel: string;
};

const PROVIDER_DEFAULTS: Record<ProviderType, ProviderDefaults> = {
  openai: {
    embeddingModel: "text-embedding-3-small",
    embeddingProvider: "openai",
    llmModel: "gpt-4o-mini",
  },
  google: {
    embeddingModel: "gemini-embedding-001",
    embeddingProvider: "google",
    llmModel: "gemini-2.0-flash",
  },
  anthropic: {
    embeddingModel: "text-embedding-3-small",
    embeddingProvider: "openai",
    llmModel: "claude-sonnet-4",
  },
  ollama: {
    embeddingModel: "nomic-embed-text",
    embeddingProvider: "ollama",
    llmModel: "llama3.2",
  },
};

type GeneratedConfig = {
  qdrant: {
    url: string;
    collectionPrefix: string;
  };
  embeddings: {
    provider: ProviderType;
    model: string;
    batchSize: number;
    timeoutMs: number;
    maxRetries: number;
    baseUrl?: string;
  };
  llm: {
    provider: ProviderType;
    model: string;
    temperature: number;
    maxTokens: number;
    timeoutMs: number;
    maxRetries: number;
    baseUrl?: string;
  };
  sync: {
    concurrency: number;
  };
  maxFileSize: number;
};

type InitRuntimeState = {
  provider: ProviderType;
  ollamaBaseUrl?: string;
};

type ApiKeyRequirement = {
  label: string;
  envVar: string;
};

const DEFAULT_QDRANT_URL = "http://localhost:6333";
const DEFAULT_COLLECTION_PREFIX = "mgrep_";
const DEFAULT_BATCH_SIZE = 100;
const DEFAULT_EMBED_TIMEOUT_MS = 30000;
const DEFAULT_EMBED_MAX_RETRIES = 3;
const DEFAULT_LLM_TEMPERATURE = 0.7;
const DEFAULT_LLM_MAX_TOKENS = 4096;
const DEFAULT_LLM_TIMEOUT_MS = 60000;
const DEFAULT_LLM_MAX_RETRIES = 3;
const DEFAULT_SYNC_CONCURRENCY = 20;
const DEFAULT_MAX_FILE_SIZE = 10 * 1024 * 1024;

const API_KEY_REQUIREMENTS: Record<ProviderType, ApiKeyRequirement[]> = {
  openai: [{ label: "OpenAI", envVar: "OPENAI_API_KEY" }],
  google: [{ label: "Google", envVar: "GOOGLE_API_KEY" }],
  anthropic: [
    { label: "Anthropic", envVar: "ANTHROPIC_API_KEY" },
    { label: "OpenAI (embeddings)", envVar: "OPENAI_API_KEY" },
  ],
  ollama: [],
};

const NEXT_STEPS = [
  "Start Qdrant: make qdrant-start",
  "Then sync files: mgrep sync",
];

function validateApiKeyFormat(provider: ProviderType, apiKey: string): boolean {
  const trimmed = apiKey.trim();
  if (!trimmed) return false;

  switch (provider) {
    case "openai":
      return trimmed.startsWith("sk-");
    case "anthropic":
      return trimmed.startsWith("sk-ant-");
    case "google":
      return trimmed.length > 10;
    case "ollama":
      return true;
    default:
      return false;
  }
}

function buildConfig(state: InitRuntimeState): GeneratedConfig {
  const defaults = PROVIDER_DEFAULTS[state.provider];
  const config: GeneratedConfig = {
    qdrant: {
      url: DEFAULT_QDRANT_URL,
      collectionPrefix: DEFAULT_COLLECTION_PREFIX,
    },
    embeddings: {
      provider: defaults.embeddingProvider,
      model: defaults.embeddingModel,
      batchSize: DEFAULT_BATCH_SIZE,
      timeoutMs: DEFAULT_EMBED_TIMEOUT_MS,
      maxRetries: DEFAULT_EMBED_MAX_RETRIES,
    },
    llm: {
      provider: state.provider,
      model: defaults.llmModel,
      temperature: DEFAULT_LLM_TEMPERATURE,
      maxTokens: DEFAULT_LLM_MAX_TOKENS,
      timeoutMs: DEFAULT_LLM_TIMEOUT_MS,
      maxRetries: DEFAULT_LLM_MAX_RETRIES,
    },
    sync: {
      concurrency: DEFAULT_SYNC_CONCURRENCY,
    },
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
  };

  if (state.provider === "ollama" && state.ollamaBaseUrl) {
    config.embeddings.baseUrl = state.ollamaBaseUrl;
    config.llm.baseUrl = state.ollamaBaseUrl;
  }

  return config;
}

function writeConfigFile(config: GeneratedConfig): void {
  fs.mkdirSync(CONFIG_DIR, { recursive: true });
  const yamlBody = YAML.stringify(config);
  const header = "# mgrep configuration - generated by mgrep init\n\n";
  fs.writeFileSync(CONFIG_FILE, `${header}${yamlBody}`, "utf-8");
}

export const initCommand = new Command("init")
  .description("Initialize mgrep configuration interactively")
  .option("--reconfigure", "Overwrite existing configuration", false)
  .action(async (options) => {
    p.intro("mgrep configuration wizard");

    if (fs.existsSync(CONFIG_FILE) && !options.reconfigure) {
      const overwrite = await p.confirm({
        message: "Configuration already exists. Overwrite?",
        initialValue: false,
      });

      if (p.isCancel(overwrite)) {
        p.cancel("Configuration cancelled.");
        return;
      }

      if (!overwrite) {
        p.cancel("Configuration cancelled.");
        return;
      }
    }

    const provider = await p.select({
      message: "Select your provider:",
      options: [
        { value: "openai", label: "OpenAI", hint: "GPT-4, text-embedding-3" },
        { value: "google", label: "Google", hint: "Gemini models" },
        { value: "anthropic", label: "Anthropic", hint: "Claude models" },
        { value: "ollama", label: "Ollama", hint: "Local models" },
      ],
    });

    if (p.isCancel(provider)) {
      p.cancel("Configuration cancelled.");
      return;
    }

    const defaults = PROVIDER_DEFAULTS[provider];
    p.note(
      `Embeddings: ${defaults.embeddingProvider} (${defaults.embeddingModel})\n` +
        `LLM: ${defaults.llmModel}`,
      "Defaults",
    );

    if (provider === "anthropic") {
      p.note(
        "Anthropic does not provide embeddings. OpenAI will be used for embeddings.",
        "Note",
      );
    }

    let ollamaBaseUrl: string | undefined;

    if (provider === "ollama") {
      const baseUrl = await p.text({
        message: "Ollama base URL:",
        initialValue: "http://localhost:11434/v1",
      });

      if (p.isCancel(baseUrl)) {
        p.cancel("Configuration cancelled.");
        return;
      }

      ollamaBaseUrl = baseUrl.trim();
      p.note(`Using ${ollamaBaseUrl}`, "Ollama");
    } else {
      const apiKey = await p.password({
        message: `Enter your ${provider} API key:`,
        validate(value) {
          return validateApiKeyFormat(provider, value)
            ? undefined
            : "API key format looks invalid.";
        },
      });

      if (p.isCancel(apiKey)) {
        p.cancel("Configuration cancelled.");
        return;
      }
    }

    const config = buildConfig({ provider, ollamaBaseUrl });
    writeConfigFile(config);

    p.note(`Configuration saved to ${CONFIG_FILE}`, "Success");

    const apiKeyRequirements = API_KEY_REQUIREMENTS[provider];
    if (apiKeyRequirements.length === 0) {
      p.note("No API key required.", "API Keys");
    } else {
      const lines = apiKeyRequirements
        .map(({ label, envVar }) => `  ${label}: export ${envVar}=...`)
        .join("\n");
      p.note(lines, "Required API Keys");
    }

    p.note(NEXT_STEPS.join("\n"), "Next Steps");
    p.outro("Configuration complete!");
  });
