import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import * as p from "@clack/prompts";
import { Command } from "commander";
import YAML from "yaml";
import { runConfigTUI } from "../lib/config-tui.js";

export function getConfigPaths() {
  const configDir = path.join(os.homedir(), ".config", "mgrep");
  const configFile = path.join(configDir, "config.yaml");
  return { configDir, configFile };
}

export type ProviderType = "openai" | "google" | "anthropic" | "ollama";

type ProviderDefaults = {
  embeddingModel: string;
  embeddingProvider: ProviderType;
  llmModel: string;
};

export const PROVIDER_DEFAULTS: Record<ProviderType, ProviderDefaults> = {
  openai: {
    embeddingModel: "text-embedding-3-small",
    embeddingProvider: "openai",
    llmModel: "gpt-4o-mini",
  },
  google: {
    embeddingModel: "gemini-embedding-001",
    embeddingProvider: "google",
    llmModel: "gemini-2.0-flash",
  },
  anthropic: {
    embeddingModel: "text-embedding-3-small",
    embeddingProvider: "openai",
    llmModel: "claude-sonnet-4",
  },
  ollama: {
    embeddingModel: "nomic-embed-text",
    embeddingProvider: "ollama",
    llmModel: "llama3.2",
  },
};

export type GeneratedConfig = {
  qdrant: {
    url: string;
    collectionPrefix: string;
  };
  embeddings: {
    provider: ProviderType;
    model: string;
    batchSize: number;
    timeoutMs: number;
    maxRetries: number;
    baseUrl?: string;
  };
  llm: {
    provider: ProviderType;
    model: string;
    temperature: number;
    maxTokens: number;
    timeoutMs: number;
    maxRetries: number;
    baseUrl?: string;
  };
  sync: {
    concurrency: number;
  };
  maxFileSize: number;
};

export type InitRuntimeState = {
  provider: ProviderType;
  ollamaBaseUrl?: string;
};

const DEFAULT_QDRANT_URL = "http://localhost:6333";
const DEFAULT_COLLECTION_PREFIX = "mgrep_";
const DEFAULT_BATCH_SIZE = 100;
const DEFAULT_EMBED_TIMEOUT_MS = 30000;
const DEFAULT_EMBED_MAX_RETRIES = 3;
const DEFAULT_LLM_TEMPERATURE = 0.7;
const DEFAULT_LLM_MAX_TOKENS = 4096;
const DEFAULT_LLM_TIMEOUT_MS = 60000;
const DEFAULT_LLM_MAX_RETRIES = 3;
const DEFAULT_SYNC_CONCURRENCY = 20;
const DEFAULT_MAX_FILE_SIZE = 10 * 1024 * 1024;

export function validateApiKeyFormat(
  provider: ProviderType,
  apiKey: string,
): boolean {
  const trimmed = apiKey.trim();
  if (!trimmed) return false;

  switch (provider) {
    case "openai":
      return trimmed.startsWith("sk-");
    case "anthropic":
      return trimmed.startsWith("sk-ant-");
    case "google":
      return trimmed.length > 10;
    case "ollama":
      return true;
    default:
      return false;
  }
}

export function buildConfig(state: InitRuntimeState): GeneratedConfig {
  const defaults = PROVIDER_DEFAULTS[state.provider];
  const config: GeneratedConfig = {
    qdrant: {
      url: DEFAULT_QDRANT_URL,
      collectionPrefix: DEFAULT_COLLECTION_PREFIX,
    },
    embeddings: {
      provider: defaults.embeddingProvider,
      model: defaults.embeddingModel,
      batchSize: DEFAULT_BATCH_SIZE,
      timeoutMs: DEFAULT_EMBED_TIMEOUT_MS,
      maxRetries: DEFAULT_EMBED_MAX_RETRIES,
    },
    llm: {
      provider: state.provider,
      model: defaults.llmModel,
      temperature: DEFAULT_LLM_TEMPERATURE,
      maxTokens: DEFAULT_LLM_MAX_TOKENS,
      timeoutMs: DEFAULT_LLM_TIMEOUT_MS,
      maxRetries: DEFAULT_LLM_MAX_RETRIES,
    },
    sync: {
      concurrency: DEFAULT_SYNC_CONCURRENCY,
    },
    maxFileSize: DEFAULT_MAX_FILE_SIZE,
  };

  if (state.provider === "ollama" && state.ollamaBaseUrl) {
    config.embeddings.baseUrl = state.ollamaBaseUrl;
    config.llm.baseUrl = state.ollamaBaseUrl;
  }

  return config;
}

export function writeConfigFile(config: GeneratedConfig): void {
  const { configDir, configFile } = getConfigPaths();
  fs.mkdirSync(configDir, { recursive: true });
  const yamlBody = YAML.stringify(config);
  const header = "# mgrep configuration - generated by mgrep init\n\n";
  fs.writeFileSync(configFile, `${header}${yamlBody}`, "utf-8");
}

export const initCommand = new Command("init")
  .description("Initialize mgrep configuration interactively")
  .option("--reconfigure", "Overwrite existing configuration", false)
  .action(async (options) => {
    const { configFile } = getConfigPaths();

    if (fs.existsSync(configFile) && !options.reconfigure) {
      p.note(`Config already exists at ${configFile}`, "mgrep");
      const overwrite = await p.confirm({
        message: "Overwrite?",
        initialValue: false,
      });

      if (p.isCancel(overwrite) || !overwrite) {
        return;
      }
    }

    await runConfigTUI(process.cwd(), "global");
  });
